@php
    $hero = $page->hero_config ?? [];
    $desktopMedia = $page->getMedia('hero_desktop');
    $mobileMedia = $page->getMedia('hero_mobile');
@endphp

<div class="row">
    <div class="col-md-8 mb-3"><div class="card border shadow-none h-100"><div class="card-header bg-light py-2"><strong><i class="fas fa-file-alt text-primary mr-1"></i>Page Details</strong></div><div class="card-body"><dl class="row mb-0"><dt class="col-sm-4">Title</dt><dd class="col-sm-8">{{ $page->title }}</dd><dt class="col-sm-4">Slug</dt><dd class="col-sm-8"><code>/{{ $page->slug }}</code></dd><dt class="col-sm-4">Template</dt><dd class="col-sm-8"><span class="badge badge-light border">{{ $page->template }}</span></dd><dt class="col-sm-4">Status</dt><dd class="col-sm-8"><span class="badge badge-{{ $page->statusBadgeClass() }}">{{ $page->statusLabel() }}</span></dd><dt class="col-sm-4">Homepage</dt><dd class="col-sm-8">{{ $page->is_homepage ? 'Yes' : 'No' }}</dd><dt class="col-sm-4">Header / Footer</dt><dd class="col-sm-8">{{ $page->show_header ? 'Header On' : 'Header Off' }} / {{ $page->show_footer ? 'Footer On' : 'Footer Off' }}</dd><dt class="col-sm-4">Published At</dt><dd class="col-sm-8">{{ $page->published_at?->format('d M Y, h:i A') ?? '—' }}</dd><dt class="col-sm-4">Created By</dt><dd class="col-sm-8">{{ $page->createdBy?->name ?? '—' }}</dd><dt class="col-sm-4">Updated By</dt><dd class="col-sm-8">{{ $page->updatedBy?->name ?? '—' }}</dd></dl></div></div></div>
    <div class="col-md-4 mb-3"><div class="card border shadow-none h-100"><div class="card-header bg-light py-2"><strong><i class="fas fa-align-left text-primary mr-1"></i>Excerpt</strong></div><div class="card-body">@if($page->excerpt)<div class="page-rich-text">{!! $page->excerpt !!}</div>@else<p class="mb-0 text-muted">No excerpt provided.</p>@endif</div></div></div>
</div>

<div class="card border shadow-none mb-3"><div class="card-header bg-light py-2"><strong><i class="fas fa-image text-primary mr-1"></i>Hero Configuration</strong></div><div class="card-body"><div class="row"><div class="col-md-4 mb-2"><small class="text-muted d-block">Heading</small><strong>{{ data_get($hero, 'heading') ?: '—' }}</strong></div><div class="col-md-2 mb-2"><small class="text-muted d-block">Overlay</small><strong>{{ data_get($hero, 'overlay') !== null ? data_get($hero, 'overlay') : '—' }}</strong></div><div class="col-md-3 mb-2"><small class="text-muted d-block">Focal Position</small><strong>{{ data_get($hero, 'focal_position') ?: '—' }}</strong></div><div class="col-md-3 mb-2"><small class="text-muted d-block">Slider Mode</small><strong>{{ data_get($hero, 'slider_mode') ? 'Enabled' : 'Disabled' }}</strong></div><div class="col-md-4 mb-2"><small class="text-muted d-block">CTA Label</small><strong>{{ data_get($hero, 'cta.label') ?: '—' }}</strong></div><div class="col-md-8 mb-2"><small class="text-muted d-block">CTA URL</small><code>{{ data_get($hero, 'cta.url') ?: '—' }}</code></div></div></div></div>

@foreach(['hero_desktop' => ['label' => 'Desktop Hero Images', 'media' => $desktopMedia], 'hero_mobile' => ['label' => 'Mobile Hero Images', 'media' => $mobileMedia]] as $collection => $group)
<div class="card border shadow-none mb-3"><div class="card-header bg-light py-2"><strong><i class="fas fa-images text-primary mr-1"></i>{{ $group['label'] }} <span class="badge badge-secondary ml-1">{{ $group['media']->count() }}</span></strong></div><div class="card-body"><div class="d-flex flex-wrap" style="gap:10px;">@if($group['media']->count() > 0)@foreach($group['media'] as $media)<div class="border rounded bg-light p-1 text-center" style="width:150px;"><img src="{{ $media->getUrl() }}" alt="{{ $media->name }}" class="rounded" style="width:140px;height:90px;object-fit:cover;"><small class="text-muted d-block text-truncate mt-1" title="{{ $media->file_name }}">{{ $media->file_name }}</small></div>@endforeach @else <span class="text-muted">No media attached.</span>@endif</div></div></div>
@endforeach

<div class="alert alert-light border mb-0"><i class="fas fa-layer-group text-primary mr-1"></i>Page sections are intentionally not managed here yet. According to the schema, <code>SectionDefinition</code> and <code>PageSection</code> are the next models after Page.</div>
