@php
$isEdit=isset($campaign);
$actionUrl=$isEdit?route('admin.campaigns.update',$campaign->id):route('admin.campaigns.store');
$hero=$isEdit?($campaign->hero_config??[]):[];
@endphp
<form id="ajax-form" action="{{ $actionUrl }}" method="POST" enctype="multipart/form-data">@csrf @if($isEdit)@method('PUT')@endif
<div class="row">
<div class="col-md-8 mb-3"><label class="font-weight-bold">Title <span class="text-danger">*</span></label><input type="text" name="title" class="form-control" value="{{ old('title',$isEdit?$campaign->title:'') }}" required><div class="invalid-feedback error-title"></div></div>
<div class="col-md-4 mb-3"><label class="font-weight-bold">Status <span class="text-danger">*</span></label><select name="status" class="form-control" required>@foreach($statuses as $key=>$label)<option value="{{ $key }}" {{ old('status',$isEdit?$campaign->status:'draft')===$key?'selected':'' }}>{{ $label }}</option>@endforeach</select><div class="invalid-feedback error-status"></div></div>
<div class="col-md-6 mb-3"><label class="font-weight-bold">Slug</label><input type="text" name="slug" class="form-control" value="{{ old('slug',$isEdit?$campaign->slug:'') }}" placeholder="Leave blank to auto-generate"><div class="invalid-feedback error-slug"></div></div>
<div class="col-md-6 mb-3"><label class="font-weight-bold">Custom Route</label><input type="text" name="custom_route" class="form-control" value="{{ old('custom_route',$isEdit?$campaign->custom_route:'') }}" placeholder="/offers/october-paint-sale"><div class="invalid-feedback error-custom_route"></div><small class="text-muted">Must not collide with reserved application routes.</small></div>
<div class="col-md-12 mb-3"><label class="font-weight-bold">Summary</label><textarea name="summary" id="campaign_summary" class="form-control tinymce-editor" rows="6" data-editor-height="260">{{ old('summary',$isEdit?$campaign->summary:'') }}</textarea><div class="invalid-feedback error-summary"></div><small class="text-muted">Stored as TEXT, so TinyMCE is used.</small></div>
<div class="col-md-4 mb-3"><label class="font-weight-bold">Published At</label><input type="datetime-local" name="published_at" class="form-control" value="{{ old('published_at',$isEdit&&$campaign->published_at?$campaign->published_at->format('Y-m-d\\TH:i'):'') }}"></div>
<div class="col-md-4 mb-3"><label class="font-weight-bold">Starts At</label><input type="datetime-local" name="starts_at" class="form-control" value="{{ old('starts_at',$isEdit&&$campaign->starts_at?$campaign->starts_at->format('Y-m-d\\TH:i'):'') }}"></div>
<div class="col-md-4 mb-3"><label class="font-weight-bold">Ends At</label><input type="datetime-local" name="ends_at" class="form-control" value="{{ old('ends_at',$isEdit&&$campaign->ends_at?$campaign->ends_at->format('Y-m-d\\TH:i'):'') }}"><div class="invalid-feedback error-ends_at"></div></div>
</div>
<hr><h6 class="font-weight-bold text-primary"><i class="fas fa-image mr-1"></i>Hero Configuration</h6>
<div class="row"><div class="col-md-6 mb-3"><label class="font-weight-bold">Hero Heading</label><input type="text" name="hero_heading" class="form-control" value="{{ old('hero_heading',data_get($hero,'heading')) }}"></div><div class="col-md-6 mb-3"><label class="font-weight-bold">Hero Subheading</label><input type="text" name="hero_subheading" class="form-control" value="{{ old('hero_subheading',data_get($hero,'subheading')) }}"></div><div class="col-md-3 mb-3"><label class="font-weight-bold">Rating</label><input type="number" step="0.1" min="0" max="5" name="hero_rating" class="form-control" value="{{ old('hero_rating',data_get($hero,'rating')) }}"></div><div class="col-md-3 mb-3"><label class="font-weight-bold">Overlay %</label><input type="number" min="0" max="100" name="hero_overlay_opacity" class="form-control" value="{{ old('hero_overlay_opacity',data_get($hero,'overlay_opacity',35)) }}"></div><div class="col-md-3 mb-3"><label class="font-weight-bold">CTA Label</label><input type="text" name="hero_cta_label" class="form-control" value="{{ old('hero_cta_label',data_get($hero,'cta.label')) }}"></div><div class="col-md-3 mb-3"><label class="font-weight-bold">CTA URL</label><input type="text" name="hero_cta_url" class="form-control" value="{{ old('hero_cta_url',data_get($hero,'cta.url')) }}"></div>
<div class="col-md-3 mb-3"><label class="font-weight-bold">Embed Provider</label><select name="hero_embed_provider" class="form-control"><option value="">None</option><option value="youtube" {{ old('hero_embed_provider',data_get($hero,'embed.provider'))==='youtube'?'selected':'' }}>YouTube</option><option value="vimeo" {{ old('hero_embed_provider',data_get($hero,'embed.provider'))==='vimeo'?'selected':'' }}>Vimeo</option></select></div><div class="col-md-9 mb-3"><label class="font-weight-bold">Embed URL</label><input type="url" name="hero_embed_url" class="form-control" value="{{ old('hero_embed_url',data_get($hero,'embed.url')) }}" placeholder="https://..."><div class="invalid-feedback error-hero_embed_url"></div></div>
@foreach(['video_autoplay'=>'Autoplay','video_muted'=>'Muted','video_controls'=>'Controls','video_loop'=>'Loop'] as $field=>$label)@php($videoDefault = data_get($hero,'video.'.str_replace('video_','',$field),$field==='video_muted'||$field==='video_controls'))<div class="col-md-3 mb-3"><label class="font-weight-bold">{{ $label }}</label><select name="{{ $field }}" class="form-control"><option value="1" {{ (int)old($field,(int)$videoDefault)===1?'selected':'' }}>Yes</option><option value="0" {{ (int)old($field,(int)$videoDefault)===0?'selected':'' }}>No</option></select></div>@endforeach
</div>
<hr><h6 class="font-weight-bold text-primary"><i class="fas fa-photo-video mr-1"></i>Campaign Media</h6>
<div class="row">
<div class="col-md-12 mb-4"><label class="font-weight-bold d-block">Hero Images</label><div id="heroImagesExisting" class="d-flex flex-wrap mb-2" style="gap:10px;">@if($isEdit)@foreach($campaign->getMedia(\App\Models\Campaign::HERO_IMAGES) as $media)<div class="border rounded p-1 text-center" style="width:110px;"><img src="{{ $media->getUrl() }}" style="width:100px;height:70px;object-fit:cover" class="rounded"><label class="small text-danger d-block mt-1"><input type="checkbox" name="hero_images_remove_ids[]" value="{{ $media->id }}"> Remove</label></div>@endforeach @endif</div><div id="heroImagesPickerPreview" class="d-flex flex-wrap mb-2" style="gap:10px;"></div><div id="heroImagesUploadPreview" class="d-flex flex-wrap mb-2" style="gap:10px;"></div><input type="file" name="hero_images[]" id="hero_images" class="form-control-file" accept="image/*" multiple><button type="button" class="btn btn-outline-primary btn-sm mt-2" id="btnChooseHeroImages"><i class="fas fa-photo-video mr-1"></i>Choose Hero Images from Media</button><button type="button" class="btn btn-outline-secondary btn-sm mt-2" id="btnClearNewHeroImages">Clear New Uploads</button><button type="button" class="btn btn-outline-danger btn-sm mt-2" id="btnClearHeroImages">Remove All Existing</button><input type="hidden" name="hero_images_media_ids" id="hero_images_media_ids" value="[]"><input type="hidden" name="hero_images_clear" id="hero_images_clear" value="0"><div class="text-danger small error-hero_images_media_ids"></div></div>
<div class="col-md-4 mb-4"><label class="font-weight-bold">Hero Video</label><div id="hero_video_preview_wrap" class="mb-2 {{ $isEdit&&$campaign->hasMedia(\App\Models\Campaign::HERO_VIDEO)?'':'d-none' }}"><div class="alert alert-light border py-2 mb-1"><i class="fas fa-video mr-1"></i><span id="hero_video_preview_text">{{ $isEdit&&$campaign->hasMedia(\App\Models\Campaign::HERO_VIDEO)?$campaign->getFirstMedia(\App\Models\Campaign::HERO_VIDEO)?->file_name:'No video selected' }}</span></div></div><input type="file" name="hero_video" id="hero_video" class="form-control-file" accept="video/mp4,video/webm"><button type="button" class="btn btn-outline-primary btn-sm mt-2" data-picker-single="hero_video" data-picker-type="video">Choose Video from Media</button><button type="button" class="btn btn-outline-danger btn-sm mt-2" data-remove-single="hero_video">Remove</button><input type="hidden" name="hero_video_media_id" id="hero_video_media_id"><input type="hidden" name="hero_video_remove" id="hero_video_remove" value="0"></div>
@foreach([\App\Models\Campaign::HERO_VIDEO_POSTER=>'Hero Video Poster',\App\Models\Campaign::SOCIAL_IMAGE=>'Social Image'] as $collection=>$label)<div class="col-md-4 mb-4"><label class="font-weight-bold">{{ $label }}</label><div id="{{ $collection }}_preview_wrap" class="mb-2 {{ $isEdit&&$campaign->hasMedia($collection)?'':'d-none' }}"><img id="{{ $collection }}_preview" src="{{ $isEdit&&$campaign->hasMedia($collection)?$campaign->getFirstMediaUrl($collection):'' }}" class="border rounded" style="width:150px;height:90px;object-fit:cover"></div><input type="file" name="{{ $collection }}" id="{{ $collection }}" class="form-control-file" accept="image/*"><button type="button" class="btn btn-outline-primary btn-sm mt-2" data-picker-single="{{ $collection }}" data-picker-type="image">Choose from Media</button><button type="button" class="btn btn-outline-danger btn-sm mt-2" data-remove-single="{{ $collection }}">Remove</button><input type="hidden" name="{{ $collection }}_media_id" id="{{ $collection }}_media_id"><input type="hidden" name="{{ $collection }}_remove" id="{{ $collection }}_remove" value="0"><div class="text-danger small error-{{ $collection }}_media_id"></div></div>@endforeach
</div>
<div class="text-right border-top pt-3"><button type="button" class="btn btn-light border font-weight-bold px-4 mr-2" data-dismiss="modal">Cancel</button><button type="submit" class="btn btn-primary font-weight-bold px-5"><i class="fas fa-save mr-1"></i>{{ $isEdit?'Update Campaign':'Save Campaign' }}</button></div>
</form>
