<script>
$(function(){
 $.ajaxSetup({headers:{'X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')}});
 const $page=$('#campaign-manager'),$wrapper=$('#content-wrapper'),$modal=$('#ajaxModal'),$body=$('#modal-body'); let timer=null;
 const toast=(m,t='success')=>window.showAlert?window.showAlert(m,t):Promise.resolve(); const confirmBox=(title,text)=>window.showConfirm?window.showConfirm({title,text}):Promise.resolve({isConfirmed:window.confirm(text)}); const fail=(x,m='Request failed.')=>toast(x.responseJSON?.message||m,'error');
 function url(){const $f=$('#filterForm'),q=$f.serialize();return q?$f.attr('action')+'?'+q:$f.attr('action')}
 function loadData(u=null){$wrapper.addClass('loading');$.get(u||url()).done(r=>$wrapper.html(r.html)).fail(fail).always(()=>$wrapper.removeClass('loading'))}
 function destroyEditors(){if(!window.tinymce)return;$body.find('textarea.tinymce-editor').each(function(){const e=this.id?tinymce.get(this.id):null;if(e)e.remove();delete this.dataset.tinymceInitialized})}
 function initializeForm(){document.dispatchEvent(new CustomEvent('admin:content-updated'))}
 function openModal(u,title){destroyEditors();$('#modal-title').text(title);$body.html('<div class="text-center py-5"><i class="fas fa-spinner fa-spin fa-3x text-primary"></i></div>');$modal.modal({backdrop:'static',keyboard:false,show:true});$.get(u).done(r=>{$body.html(r.html);initializeForm()}).fail(x=>$body.html('<div class="alert alert-danger">'+(x.responseJSON?.message||'Failed to load content.')+'</div>'))}
 $('#btnAddRecord').on('click',()=>openModal($page.data('create-url'),'Create Campaign')); $(document).on('click','.btn-edit',function(){openModal($(this).data('url'),'Edit Campaign')}); $(document).on('click','.btn-show',function(){openModal($(this).data('url'),'Campaign Details')}); $(document).on('click','.btn-preview',function(){openModal($(this).data('url'),'Campaign Preview')});
 $(document).on('submit','#filterForm',e=>{e.preventDefault();loadData()}); $(document).on('change','#filter_status,#filter_default',()=>loadData()); $(document).on('input','#table_search',function(){clearTimeout(timer);timer=setTimeout(()=>loadData(),350)}); $('#btnResetFilter').on('click',function(){document.getElementById('filterForm')?.reset();loadData()}); $(document).on('click','#content-wrapper .pagination a',function(e){e.preventDefault();loadData($(this).attr('href'))}); $(document).on('change','#checkAll',function(){$('.row-checkbox').prop('checked',this.checked)});
 function validation($f,x){if(x.status!==422||!x.responseJSON?.errors)return false;Object.entries(x.responseJSON.errors).forEach(([k,msgs])=>{const base=k.split('.')[0],$field=$f.find('[name="'+k+'"],[name="'+base+'"],[name="'+base+'[]"]').first();$field.addClass('is-invalid');$f.find('.error-'+k.replace(/\./g,'_')+',.error-'+base).first().text(msgs[0]).show()});toast(Object.values(x.responseJSON.errors)[0][0],'error');return true}
 $(document).on('submit','#ajax-form',function(e){e.preventDefault();if(window.tinymce)tinymce.triggerSave();const form=this,$f=$(form),$btn=$f.find('button[type="submit"]');$f.find('.is-invalid').removeClass('is-invalid');$f.find('[class*="error-"]').text('');$btn.prop('disabled',true);$.ajax({url:$f.attr('action'),type:'POST',data:new FormData(form),processData:false,contentType:false}).done(r=>{$modal.modal('hide');toast(r.message);loadData()}).fail(x=>{if(!validation($f,x))fail(x)}).always(()=>$btn.prop('disabled',false))});
 function action(sel,method,title,text){$(document).on('click',sel,function(){const u=$(this).data('url');confirmBox(title,text).then(r=>{if(!r.isConfirmed)return;$.ajax({url:u,type:method}).done(x=>{toast(x.message);loadData()}).fail(fail)})})}
 action('.btn-delete','DELETE','Move Campaign to Trash?','It can be restored later.');action('.btn-restore','POST','Restore Campaign?','Restore as non-default?');action('.btn-force-delete','DELETE','Permanently Delete Campaign?','Campaign media and sections will be permanently removed.');action('.btn-publish','POST','Publish Campaign?','Make this campaign eligible for public use?');action('.btn-unpublish','POST','Unpublish Campaign?','Move this campaign back to Draft?');action('.btn-default','POST','Set Default Campaign?','This replaces the current default campaign.');action('.btn-duplicate','POST','Duplicate Campaign?','A Draft copy will be created.');
 $('#btnApplyBulk').on('click',function(){const action=$('#bulk_action').val(),ids=$('.row-checkbox:checked').map(function(){return this.value}).get();if(!action)return toast('Select a bulk action.','warning');if(!ids.length)return toast('Select at least one campaign.','warning');confirmBox('Confirm Bulk Action','Apply '+action+' to '+ids.length+' campaign(s)?').then(r=>{if(!r.isConfirmed)return;$.post($page.data('bulk-url'),{action,ids}).done(x=>{toast(x.message);loadData()}).fail(fail)})});
 $(document).on('click','#btnChooseHeroImages',function(){if(!window.MediaPicker)return toast('Media Picker is not available.','error');MediaPicker.open(function(selected){const items=(Array.isArray(selected)?selected:[selected]).filter(Boolean);$('#hero_images_media_ids').val(JSON.stringify(items.map(x=>x.id)));renderPickedHero(items)},{type:'image',multiple:true,max:12,title:'Choose Campaign Hero Images'})});
 function renderPickedHero(items){const $p=$('#heroImagesPickerPreview').empty();items.forEach(x=>$p.append('<div class="border rounded p-1 text-center picked-hero-item" data-id="'+x.id+'"><img src="'+x.url+'" style="width:100px;height:70px;object-fit:cover" class="rounded"><button type="button" class="btn btn-link btn-sm text-danger p-0 d-block mx-auto btn-remove-picked-hero">Remove</button></div>'))}
 $(document).on('click','.btn-remove-picked-hero',function(){const id=String($(this).closest('.picked-hero-item').data('id'));let ids=[];try{ids=JSON.parse($('#hero_images_media_ids').val()||'[]')}catch(e){}ids=ids.filter(x=>String(x)!==id);$('#hero_images_media_ids').val(JSON.stringify(ids));$(this).closest('.picked-hero-item').remove()});
 $(document).on('change','#hero_images',function(){const $p=$('#heroImagesUploadPreview').empty();Array.from(this.files||[]).forEach(file=>{const r=new FileReader();r.onload=e=>$p.append('<div class="border rounded p-1 text-center"><img src="'+e.target.result+'" style="width:100px;height:70px;object-fit:cover" class="rounded"><div class="small text-muted text-truncate" style="max-width:100px">'+$('<div>').text(file.name).html()+'</div></div>');r.readAsDataURL(file)})});
 $(document).on('click','#btnClearNewHeroImages',function(){$('#hero_images').val('');$('#heroImagesUploadPreview').empty()});
 $(document).on('click','#btnClearHeroImages',function(){$('#hero_images_clear').val('1');$('#heroImagesExisting').addClass('opacity-50')});
 $(document).on('click','[data-picker-single]',function(){const key=$(this).data('picker-single'),type=$(this).data('picker-type');if(!window.MediaPicker)return toast('Media Picker is not available.','error');MediaPicker.open(function(media){if(!media)return;$('#'+key).val('');$('#'+key+'_media_id').val(media.id);$('#'+key+'_remove').val('0');if(type==='image'){$('#'+key+'_preview').attr('src',media.url);$('#'+key+'_preview_wrap').removeClass('d-none')}else{$('#hero_video_preview_text').text(media.name||'Selected video');$('#hero_video_preview_wrap').removeClass('d-none')}},{type,multiple:false,title:'Choose '+(type==='video'?'Video':'Image')})});
 $(document).on('click','[data-remove-single]',function(){const key=$(this).data('remove-single');$('#'+key).val('');$('#'+key+'_media_id').val('');$('#'+key+'_remove').val('1');$('#'+key+'_preview_wrap').addClass('d-none')});
 $(document).on('change','#hero_video_poster,#social_image',function(){const key=this.id,file=this.files?.[0];if(!file)return;$('#'+key+'_media_id').val('');$('#'+key+'_remove').val('0');const r=new FileReader();r.onload=e=>{$('#'+key+'_preview').attr('src',e.target.result);$('#'+key+'_preview_wrap').removeClass('d-none')};r.readAsDataURL(file)}); $(document).on('change','#hero_video',function(){const file=this.files?.[0];if(file){$('#hero_video_media_id').val('');$('#hero_video_remove').val('0');$('#hero_video_preview_text').text(file.name);$('#hero_video_preview_wrap').removeClass('d-none')}});
 $modal.on('hidden.bs.modal',function(){destroyEditors();$body.empty()});
});
</script>
