@php($isTrashMode = isset($isTrash) && (bool)$isTrash)
<div class="table-responsive"><table class="table table-hover mb-0 text-nowrap"><thead class="thead-light"><tr><th class="text-center"><input id="checkAll" type="checkbox"></th><th>Campaign</th><th>Status</th><th>Schedule</th><th class="text-center">Sections</th><th class="text-center">Default</th><th>Updated</th><th class="text-center">Actions</th></tr></thead><tbody>
@forelse($campaigns as $campaign)
<tr><td class="text-center align-middle"><input class="row-checkbox" type="checkbox" value="{{ $campaign->id }}"></td><td class="align-middle"><div class="font-weight-bold">{{ $campaign->title }}</div><small class="text-muted">/{{ $campaign->slug }} @if($campaign->custom_route) · {{ $campaign->custom_route }}@endif</small></td><td class="align-middle"><span class="badge badge-{{ $campaign->statusBadgeClass() }}">{{ $campaign->statusLabel() }}</span></td><td class="align-middle small">@if($campaign->starts_at){{ $campaign->starts_at->format('d M Y H:i') }}@else Any time @endif @if($campaign->ends_at)<br><span class="text-muted">to {{ $campaign->ends_at->format('d M Y H:i') }}</span>@endif</td><td class="text-center align-middle">{{ $campaign->sections_count ?? 0 }}</td><td class="text-center align-middle">@if((int)$defaultCampaignId===(int)$campaign->id)<span class="badge badge-success"><i class="fas fa-star mr-1"></i>Default</span>@else — @endif</td><td class="align-middle small">{{ $campaign->updated_at?->format('d M Y H:i') }}</td><td class="text-center align-middle">
@if($isTrashMode)
@can('campaign_restore')<button type="button" class="btn btn-sm btn-outline-success btn-restore" data-url="{{ route('admin.campaigns.restore',$campaign->id) }}" title="Restore"><i class="fas fa-undo"></i></button>@endcan
@can('campaign_force_delete')<button type="button" class="btn btn-sm btn-outline-danger btn-force-delete" data-url="{{ route('admin.campaigns.force_delete',$campaign->id) }}" title="Force Delete"><i class="fas fa-trash"></i></button>@endcan
@else
@can('campaign_view')<button type="button" class="btn btn-sm btn-outline-info btn-show" data-url="{{ route('admin.campaigns.show',$campaign->id) }}" title="View"><i class="fas fa-eye"></i></button>@endcan
@can('campaign_update')<button type="button" class="btn btn-sm btn-outline-primary btn-edit" data-url="{{ route('admin.campaigns.edit',$campaign->id) }}" title="Edit"><i class="fas fa-pen"></i></button>@endcan
@can('campaign_section_list')<a class="btn btn-sm btn-outline-dark" href="{{ route('admin.campaign_sections.index',['campaign_id'=>$campaign->id]) }}" title="Sections"><i class="fas fa-layer-group"></i></a>@endcan
@can('campaign_set_default')@if((int)$defaultCampaignId!==(int)$campaign->id)<button type="button" class="btn btn-sm btn-outline-success btn-default" data-url="{{ route('admin.campaigns.set_default',$campaign->id) }}" title="Set Default"><i class="fas fa-star"></i></button>@endif @endcan
@can('campaign_publish')@if($campaign->status==='published')<button type="button" class="btn btn-sm btn-outline-warning btn-unpublish" data-url="{{ route('admin.campaigns.unpublish',$campaign->id) }}" title="Unpublish"><i class="fas fa-pause"></i></button>@else<button type="button" class="btn btn-sm btn-outline-success btn-publish" data-url="{{ route('admin.campaigns.publish',$campaign->id) }}" title="Publish"><i class="fas fa-play"></i></button>@endif @endcan
@can('campaign_create')<button type="button" class="btn btn-sm btn-outline-secondary btn-duplicate" data-url="{{ route('admin.campaigns.duplicate',$campaign->id) }}" title="Duplicate"><i class="fas fa-copy"></i></button>@endcan
@can('campaign_delete')<button type="button" class="btn btn-sm btn-outline-danger btn-delete" data-url="{{ route('admin.campaigns.destroy',$campaign->id) }}" title="Trash"><i class="fas fa-trash"></i></button>@endcan
@endif
</td></tr>
@empty<tr><td colspan="8" class="text-center py-5 text-muted">No campaigns found.</td></tr>@endforelse
</tbody></table></div>@if($campaigns->hasPages())<div class="p-3">{{ $campaigns->links('pagination::bootstrap-4') }}</div>@endif
