<script>
$(function(){
 $.ajaxSetup({headers:{'X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')}});const $page=$('#campaign-section-manager'),$wrapper=$('#content-wrapper'),$modal=$('#ajaxModal'),$body=$('#modal-body');let timer=null;const toast=(m,t='success')=>window.showAlert?window.showAlert(m,t):Promise.resolve();const confirmBox=(title,text)=>window.showConfirm?window.showConfirm({title,text}):Promise.resolve({isConfirmed:window.confirm(text)});const fail=(x,m='Request failed.')=>toast(x.responseJSON?.message||m,'error');function url(){const $f=$('#filterForm'),q=$f.serialize();return q?$f.attr('action')+'?'+q:$f.attr('action')}function loadData(u=null){$wrapper.addClass('loading');$.get(u||url()).done(r=>$wrapper.html(r.html)).fail(fail).always(()=>$wrapper.removeClass('loading'))}function openModal(u,title){$('#modal-title').text(title);$modal.modal({backdrop:'static',keyboard:false,show:true});$body.html('<div class="text-center py-5"><i class="fas fa-spinner fa-spin fa-2x"></i></div>');$.get(u).done(r=>{$body.html(r.html);if($.fn.select2)$body.find('.select2').select2({width:'100%',dropdownParent:$modal})}).fail(fail)}
 $('#btnAddRecord').on('click',()=>openModal($page.data('create-url')+($('#filter_campaign').val()?'?campaign_id='+$('#filter_campaign').val():''),'Create Campaign Section'));$(document).on('click','.btn-edit',function(){openModal($(this).data('url'),'Edit Campaign Section')});$(document).on('click','.btn-show',function(){openModal($(this).data('url'),'Campaign Section Details')});$(document).on('change','#filter_campaign,#filter_type',()=>loadData());$(document).on('input','#table_search',function(){clearTimeout(timer);timer=setTimeout(()=>loadData(),350)});$('#btnResetFilter').on('click',function(){document.getElementById('filterForm')?.reset();loadData()});$(document).on('click','#content-wrapper .pagination a',function(e){e.preventDefault();loadData($(this).attr('href'))});$(document).on('change','#checkAll',function(){$('.row-checkbox').prop('checked',this.checked)});
 $(document).on('submit','#ajax-form',function(e){e.preventDefault();const form=this,$f=$(form),$b=$f.find('button[type="submit"]');$b.prop('disabled',true);$.ajax({url:$f.attr('action'),type:'POST',data:new FormData(form),processData:false,contentType:false}).done(r=>{$modal.modal('hide');toast(r.message);loadData()}).fail(x=>{if(x.status===422&&x.responseJSON?.errors){Object.entries(x.responseJSON.errors).forEach(([k,m])=>{$f.find('.error-'+k.replace(/\./g,'_')).first().text(m[0]);$f.find('[name="'+k+'"],[name="'+k.split('.')[0]+'"]').first().addClass('is-invalid')});toast(Object.values(x.responseJSON.errors)[0][0],'error')}else fail(x)}).always(()=>$b.prop('disabled',false))});
 function action(sel,method,title,text){$(document).on('click',sel,function(){const u=$(this).data('url');confirmBox(title,text).then(r=>{if(!r.isConfirmed)return;$.ajax({url:u,type:method}).done(x=>{toast(x.message);loadData()}).fail(fail)})})} action('.btn-delete','DELETE','Move Section to Trash?','You can restore it later.');action('.btn-restore','POST','Restore Section?','Restore this section?');action('.btn-force-delete','DELETE','Permanently Delete Section?','This cannot be undone.');action('.btn-toggle','POST','Toggle Section?','Change this section visibility?');action('.btn-duplicate','POST','Duplicate Section?','Create a copy in the same campaign?');
 $('#btnApplyBulk').on('click',function(){const action=$('#bulk_action').val(),ids=$('.row-checkbox:checked').map(function(){return this.value}).get();if(!action)return toast('Select a bulk action.','warning');if(!ids.length)return toast('Select at least one section.','warning');confirmBox('Confirm Bulk Action','Apply '+action+' to '+ids.length+' section(s)?').then(r=>{if(!r.isConfirmed)return;$.post($page.data('bulk-url'),{action,ids}).done(x=>{toast(x.message);loadData()}).fail(fail)})});
 $('#btnSaveOrder').on('click',function(){const campaignId=$('#filter_campaign').val();if(!campaignId)return toast('Filter by one campaign before saving order.','warning');const order=[];$('#content-wrapper tr[data-section-id]').each(function(){order.push({id:$(this).data('section-id'),sort_order:$(this).find('.section-order-input').val()})});if(!order.length)return toast('No sections to reorder.','warning');$.post($page.data('reorder-url'),{campaign_id:campaignId,order}).done(x=>{toast(x.message);loadData()}).fail(fail)});
});
</script>
