@php($isEdit=isset($trackingEventRule))
<form id="ajax-form" action="{{ $isEdit?route('admin.tracking_event_rules.update',$trackingEventRule->id):route('admin.tracking_event_rules.store') }}" method="POST">@csrf @if($isEdit) @method('PUT') @endif
<div class="row">
<div class="col-md-6 mb-3"><label class="font-weight-bold">Tracking Provider <span class="text-danger">*</span></label><select name="tracking_provider_id" class="form-control" required>@foreach($providers as $provider)<option value="{{ $provider->id }}" {{ (string)old('tracking_provider_id',$isEdit?$trackingEventRule->tracking_provider_id:'')===(string)$provider->id?'selected':'' }}>{{ $provider->label() }}</option>@endforeach</select><div class="invalid-feedback error-tracking_provider_id"></div></div>
<div class="col-md-6 mb-3"><label class="font-weight-bold">Internal Event <span class="text-danger">*</span></label><select name="internal_event" class="form-control" required>@foreach($events as $key=>$label)<option value="{{ $key }}" {{ old('internal_event',$isEdit?$trackingEventRule->internal_event:'')===$key?'selected':'' }}>{{ $label }} ({{ $key }})</option>@endforeach</select><div class="invalid-feedback error-internal_event"></div></div>
<div class="col-md-12 mb-3"><label class="font-weight-bold">Provider Event <span class="text-danger">*</span></label><input type="text" name="provider_event" class="form-control" maxlength="120" value="{{ old('provider_event',$isEdit?$trackingEventRule->provider_event:'') }}" placeholder="PageView, Lead, generate_lead..." required><div class="invalid-feedback error-provider_event"></div></div>
<div class="col-md-12 mb-3"><label class="font-weight-bold">Parameter Map JSON</label><textarea name="parameter_map" class="form-control text-monospace" rows="8" placeholder='{"value":"lead.pricing_total","currency":"site.currency"}'>{{ old('parameter_map',$isEdit&&$trackingEventRule->parameter_map?json_encode($trackingEventRule->parameter_map,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES):'') }}</textarea><div class="invalid-feedback error-parameter_map"></div></div>
<div class="col-md-6 mb-3"><label class="font-weight-bold">Requires Marketing Consent</label><select name="requires_marketing_consent" class="form-control"><option value="1" {{ (string)old('requires_marketing_consent',$isEdit?(int)$trackingEventRule->requires_marketing_consent:1)==='1'?'selected':'' }}>Yes</option><option value="0" {{ (string)old('requires_marketing_consent',$isEdit?(int)$trackingEventRule->requires_marketing_consent:1)==='0'?'selected':'' }}>No</option></select></div>
<div class="col-md-6 mb-3"><label class="font-weight-bold">Enabled</label><select name="is_enabled" class="form-control"><option value="1" {{ (string)old('is_enabled',$isEdit?(int)$trackingEventRule->is_enabled:1)==='1'?'selected':'' }}>Yes</option><option value="0" {{ (string)old('is_enabled',$isEdit?(int)$trackingEventRule->is_enabled:1)==='0'?'selected':'' }}>No</option></select></div>
</div>
<div class="text-right border-top pt-3"><button type="button" class="btn btn-light border mr-2" data-dismiss="modal">Cancel</button><button type="submit" class="btn btn-primary font-weight-bold px-4"><i class="fas fa-save mr-1"></i>{{ $isEdit?'Update Rule':'Save Rule' }}</button></div>
</form>