@extends('backoffice.admin.layouts.app')
@section('title', $title)
@section('content')
<div id="audit-manager" class="container-fluid py-3" data-index-url="{{ route('admin.audit_logs.trashed') }}" data-bulk-url="{{ route('admin.audit_logs.multiple_action') }}">
    <div class="d-flex align-items-center flex-wrap mb-3" style="gap:6px;"><a href="{{ route('admin.audit_logs.index') }}" class="btn btn-secondary btn-sm font-weight-bold"><i class="fas fa-arrow-left mr-1"></i>Back</a><select id="bulk_action" class="form-control form-control-sm" style="width:210px;"><option value="">-- Bulk Actions --</option>@can('audit_log_restore')<option value="restore">Restore Selected</option>@endcan @can('audit_log_force_delete')<option value="force_delete">Permanently Delete</option>@endcan</select><button type="button" class="btn btn-secondary btn-sm font-weight-bold px-3" id="btnApplyBulk">APPLY</button></div>
    <div class="card shadow-sm border-0 mb-3"><div class="card-body px-3 py-2"><form id="filterForm" action="{{ route('admin.audit_logs.trashed') }}" method="GET"><div class="row align-items-end"><div class="col-md-3"><label class="small text-muted font-weight-bold">ACTION</label><select name="action" id="filter_action" class="form-control form-control-sm"><option value="">All Actions</option>@foreach($actions as $action)<option value="{{ $action }}">{{ $action }}</option>@endforeach</select></div><div class="col-md-8"><label class="small text-muted font-weight-bold">SEARCH</label><input type="search" name="search" id="table_search" class="form-control form-control-sm" placeholder="Action, model, IP..."></div><div class="col-md-1"><button type="button" id="btnResetFilter" class="btn btn-outline-danger btn-sm btn-block"><i class="fas fa-sync-alt"></i></button></div></div></form></div></div>
    <div class="card shadow-sm border-0"><div class="card-header bg-white text-danger"><h3 class="card-title font-weight-bold"><i class="fas fa-trash-alt mr-1"></i>Audit Log Trash</h3></div><div class="card-body p-0" id="content-wrapper">@include('backoffice.admin.audit_logs.partials.table',['auditLogs'=>$auditLogs,'isTrash'=>true])</div></div>
</div>
<div class="modal fade" id="ajaxModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content"><div class="modal-header border-0"><h5 class="modal-title font-weight-bold text-primary" id="modal-title">Audit Log</h5><button class="close" data-dismiss="modal">&times;</button></div><div class="modal-body" id="modal-body"></div></div></div></div>
@endsection
@section('plugins.Sweetalert2', true)
@section('js') @include('backoffice.admin.audit_logs.partials.script') @endsection
