@extends('backoffice.admin.layouts.app')
@section('title',$title)
@section('content')
<div id="tracking-rule-manager" class="container-fluid py-3" data-index-url="{{ route('admin.tracking_event_rules.index') }}" data-create-url="{{ route('admin.tracking_event_rules.create') }}" data-bulk-url="{{ route('admin.tracking_event_rules.multiple_action') }}">
<div class="d-flex flex-wrap mb-3" style="gap:6px">@can('tracking_event_rule_create')<button id="btnAddRecord" class="btn btn-primary btn-sm font-weight-bold"><i class="fas fa-plus mr-1"></i>Add Event Rule</button>@endcan @can('tracking_event_rule_trash')<a href="{{ route('admin.tracking_event_rules.trashed') }}" class="btn btn-outline-danger btn-sm font-weight-bold"><i class="fas fa-trash-alt mr-1"></i>Trash Bin</a>@endcan <select id="bulk_action" class="form-control form-control-sm" style="width:190px"><option value="">-- Bulk Actions --</option>@can('tracking_event_rule_toggle')<option value="enable">Enable</option><option value="disable">Disable</option>@endcan @can('tracking_event_rule_delete')<option value="delete">Move to Trash</option>@endcan</select><button id="btnApplyBulk" class="btn btn-secondary btn-sm">APPLY</button></div>
<div class="card border-0 shadow-sm mb-3"><div class="card-body py-2"><form id="filterForm" action="{{ route('admin.tracking_event_rules.index') }}"><div class="row align-items-end">
<div class="col-md-3"><label class="small text-muted font-weight-bold">PROVIDER</label><select id="filter_provider_id" name="provider_id" class="form-control form-control-sm"><option value="">All Providers</option>@foreach($providers as $provider)<option value="{{ $provider->id }}" {{ (string)request('provider_id')===(string)$provider->id?'selected':'' }}>{{ $provider->label() }}</option>@endforeach</select></div>
<div class="col-md-3"><label class="small text-muted font-weight-bold">INTERNAL EVENT</label><select id="filter_internal_event" name="internal_event" class="form-control form-control-sm"><option value="">All Events</option>@foreach($events as $key=>$label)<option value="{{ $key }}" {{ request('internal_event')===$key?'selected':'' }}>{{ $label }}</option>@endforeach</select></div>
<div class="col-md-2"><label class="small text-muted font-weight-bold">STATUS</label><select id="filter_status" name="status" class="form-control form-control-sm"><option value="">All</option><option value="enabled" {{ request('status')==='enabled'?'selected':'' }}>Enabled</option><option value="disabled" {{ request('status')==='disabled'?'selected':'' }}>Disabled</option></select></div>
<div class="col-md-3"><label class="small text-muted font-weight-bold">SEARCH</label><input id="table_search" name="search" class="form-control form-control-sm" value="{{ request('search') }}" placeholder="Internal/provider event..."></div>
<div class="col-md-1"><button type="button" id="btnResetFilter" class="btn btn-outline-danger btn-sm btn-block"><i class="fas fa-sync-alt"></i></button></div>
</div></form></div></div>
<div class="card border-0 shadow-sm"><div class="card-header bg-white"><h3 class="card-title font-weight-bold"><i class="fas fa-project-diagram text-primary mr-1"></i>Tracking Event Rules</h3></div><div class="card-body p-0" id="content-wrapper">@include('backoffice.admin.tracking_event_rules.partials.table',['trackingEventRules'=>$trackingEventRules,'isTrash'=>false])</div></div>
</div>
<div class="modal fade" id="ajaxModal" data-backdrop="static" data-keyboard="false" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header border-0"><h5 id="modal-title" class="modal-title font-weight-bold text-primary"></h5><button class="close" data-dismiss="modal">&times;</button></div><div class="modal-body" id="modal-body"></div></div></div></div>
@include('backoffice.admin.tracking_event_rules.partials.script')
@endsection
@section('plugins.Sweetalert2',true)
