@extends('backoffice.admin.layouts.app')
@section('title',$title)
@section('content')
<div id="campaign-manager" class="container-fluid py-3" data-index-url="{{ route('admin.campaigns.trashed') }}" data-bulk-url="{{ route('admin.campaigns.multiple_action') }}">
<div class="d-flex align-items-center flex-wrap mb-3" style="gap:6px;"><a href="{{ route('admin.campaigns.index') }}" class="btn btn-secondary btn-sm font-weight-bold"><i class="fas fa-arrow-left mr-1"></i>Back to Campaigns</a><select id="bulk_action" class="form-control form-control-sm" style="width:210px;"><option value="">-- Bulk Actions --</option>@can('campaign_restore')<option value="restore">Restore Selected</option>@endcan @can('campaign_force_delete')<option value="force_delete">Permanently Delete</option>@endcan</select><button type="button" class="btn btn-secondary btn-sm font-weight-bold px-3" id="btnApplyBulk">APPLY</button></div>
<div class="card shadow-sm border-0 mb-3"><div class="card-body px-3 py-2"><form id="filterForm" action="{{ route('admin.campaigns.trashed') }}" method="GET"><div class="row align-items-end"><div class="col-md-3"><label class="small text-muted font-weight-bold">STATUS</label><select name="status" id="filter_status" class="form-control form-control-sm"><option value="">All Statuses</option>@foreach($statuses as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div><div class="col-md-8"><label class="small text-muted font-weight-bold">SEARCH</label><input type="search" name="search" id="table_search" class="form-control form-control-sm" placeholder="Title, slug or route..."></div><div class="col-md-1"><button type="button" id="btnResetFilter" class="btn btn-outline-danger btn-sm btn-block"><i class="fas fa-sync-alt"></i></button></div></div></form></div></div>
<div class="card shadow-sm border-0"><div class="card-header bg-white text-danger"><h3 class="card-title font-weight-bold"><i class="fas fa-trash-alt mr-1"></i>Campaign Trash</h3></div><div class="card-body p-0" id="content-wrapper">@include('backoffice.admin.campaigns.partials.table',['campaigns'=>$campaigns,'defaultCampaignId'=>null,'isTrash'=>true])</div></div>
</div>
<div class="modal fade" id="ajaxModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content"><div class="modal-header border-0"><h5 class="modal-title font-weight-bold text-primary" id="modal-title">Campaign</h5><button class="close" data-dismiss="modal">&times;</button></div><div class="modal-body" id="modal-body"></div></div></div></div>
@endsection
@section('plugins.Sweetalert2', true)
@push('css')<style>.campaign-thumb{width:72px;height:46px;object-fit:cover;border-radius:6px}</style>@endpush
@section('js') @include('backoffice.admin.campaigns.partials.script') @endsection
