<section class="hp-section hp-quote-section" id="quote-form"><div class="container">
    <div class="hp-quote-banner"><div class="hp-quote-copy"><span class="hp-eyebrow hp-eyebrow-light">Tell us about your project</span><h2>{{ $settings['contact.quote_heading'] ?? 'Request Your Site Inspection & Quote' }}</h2><p>Share your requirements and our team can review your enquiry. On-site appointments and pricing depend on availability and scope.</p>
        <ul class="hp-quote-points list-unstyled mb-0"><li><i class="bi bi-check-circle-fill"></i> Describe your property and service needs</li><li><i class="bi bi-check-circle-fill"></i> Choose any applicable options</li><li><i class="bi bi-check-circle-fill"></i> Receive a response through your contact details</li></ul>
    </div>
    <div class="hp-quote-form-wrap"><form action="{{ route('website.enquiries.store') }}" method="POST" class="hp-quote-form" autocomplete="on">
        @csrf
        @if(session('quote_success'))<div class="alert alert-success" role="status">{{ session('quote_success') }}</div>@endif
        @if($errors->any())<div class="alert alert-danger" role="alert">Please check the highlighted information.</div>@endif
        <div class="visually-hidden" aria-hidden="true"><label for="companyWebsite">Company website</label><input type="text" id="companyWebsite" name="company_website" value="" autocomplete="off" tabindex="-1"></div>
        <div class="row g-3">
            <div class="col-md-6"><label for="hpLeadName" class="form-label">Your Name <span>*</span></label><input id="hpLeadName" class="form-control @error('name') is-invalid @enderror" type="text" name="name" maxlength="190" required autocomplete="name" placeholder="Enter your full name" value="{{ old('name') }}">@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-6"><label for="hpLeadPhone" class="form-label">Your Contact Number <span>*</span></label><input id="hpLeadPhone" class="form-control @error('phone') is-invalid @enderror" type="tel" name="phone" maxlength="32" required autocomplete="tel" placeholder="e.g. +65 9123 4567" value="{{ old('phone') }}">@error('phone')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-6"><label for="hpLeadEmail" class="form-label">Email (optional)</label><input id="hpLeadEmail" class="form-control @error('email') is-invalid @enderror" type="email" name="email" maxlength="190" autocomplete="email" placeholder="you@example.com" value="{{ old('email') }}">@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            @if($services->isNotEmpty())<div class="col-md-6"><label for="hpLeadService" class="form-label">Service (optional)</label><select id="hpLeadService" name="service_id" class="form-select @error('service_id') is-invalid @enderror"><option value="" disabled @selected(!old('service_id'))>Select the service you need</option>@foreach($services as $service)<option value="{{ $service->id }}" @selected(old('service_id') == $service->id)>{{ $service->name }}</option>@endforeach</select>@error('service_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>@endif
            @foreach($fields as $field)
                <div class="col-md-6"><label class="form-label" for="hpDynamic{{ $field->id }}">{{ $field->label }} @if($field->is_required)<span>*</span>@endif</label><select class="form-select @error('dynamic_answers.'.$field->field_key) is-invalid @enderror" name="dynamic_answers[{{ $field->field_key }}]" id="hpDynamic{{ $field->id }}" @required($field->is_required)><option value="" disabled @selected(!old('dynamic_answers.'.$field->field_key))>Select {{ \Illuminate\Support\Str::lower($field->label) }}</option>@foreach(($field->options ?? []) as $option)@if(is_scalar($option))<option value="{{ $option }}" @selected(old('dynamic_answers.'.$field->field_key)==$option)>{{ $option }}</option>@endif @endforeach</select>@error('dynamic_answers.'.$field->field_key)<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            @endforeach
            <div class="col-12"><label for="hpLeadMessage" class="form-label">Your requirements (optional)</label><textarea id="hpLeadMessage" class="form-control @error('message') is-invalid @enderror" name="message" rows="3" maxlength="4000" placeholder="Describe the work needed, property type, preferred timing or special requirements...">{{ old('message') }}</textarea>@error('message')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-12"><button type="submit" class="btn btn-brand w-100"><i class="bi bi-send me-2"></i>Submit My Quote Request <i class="bi bi-arrow-right ms-1"></i></button></div>
        </div><p class="hp-form-privacy"><i class="bi bi-lock"></i> Your information is used to respond to this enquiry.</p>
    </form></div></div>
</div></section>
