@extends('backoffice.admin.layouts.app')
@section('title',$title)
@section('content')
<div id="campaign-section-manager" class="container-fluid py-3" data-index-url="{{ route('admin.campaign_sections.index') }}" data-create-url="{{ route('admin.campaign_sections.create') }}" data-bulk-url="{{ route('admin.campaign_sections.multiple_action') }}" data-reorder-url="{{ route('admin.campaign_sections.reorder') }}">
<div class="d-flex align-items-center flex-wrap mb-3" style="gap:6px;">@can('campaign_section_create')<button type="button" class="btn btn-primary btn-sm font-weight-bold" id="btnAddRecord"><i class="fas fa-plus mr-1"></i>Add Section</button>@endcan @can('campaign_section_trash')<a href="{{ route('admin.campaign_sections.trashed') }}" class="btn btn-outline-danger btn-sm font-weight-bold"><i class="fas fa-trash-alt mr-1"></i>Trash Bin</a>@endcan <select id="bulk_action" class="form-control form-control-sm" style="width:200px;"><option value="">-- Bulk Actions --</option>@can('campaign_section_toggle')<option value="enable">Enable</option><option value="disable">Disable</option>@endcan @can('campaign_section_delete')<option value="delete">Move to Trash</option>@endcan</select><button class="btn btn-secondary btn-sm font-weight-bold px-3" id="btnApplyBulk">APPLY</button>@can('campaign_section_reorder')<button class="btn btn-outline-primary btn-sm font-weight-bold ml-auto" id="btnSaveOrder"><i class="fas fa-sort-amount-down mr-1"></i>Save Order</button>@endcan</div>
<div class="card shadow-sm border-0 mb-3"><div class="card-body px-3 py-2"><form id="filterForm" action="{{ route('admin.campaign_sections.index') }}"><div class="row align-items-end"><div class="col-md-4"><label class="small text-muted font-weight-bold">CAMPAIGN</label><select name="campaign_id" id="filter_campaign" class="form-control form-control-sm"><option value="">All Campaigns</option>@foreach($campaigns as $c)<option value="{{ $c->id }}" {{ (string)request('campaign_id')===(string)$c->id?'selected':'' }}>{{ $c->title }}</option>@endforeach</select></div><div class="col-md-3"><label class="small text-muted font-weight-bold">TYPE</label><select name="section_key" id="filter_type" class="form-control form-control-sm"><option value="">All Types</option>@foreach($types as $k=>$l)<option value="{{ $k }}">{{ $l }}</option>@endforeach</select></div><div class="col-md-4"><label class="small text-muted font-weight-bold">SEARCH</label><input name="search" id="table_search" class="form-control form-control-sm" placeholder="Heading or type..."></div><div class="col-md-1"><button type="button" id="btnResetFilter" class="btn btn-outline-danger btn-sm btn-block"><i class="fas fa-sync-alt"></i></button></div></div></form></div></div>
<div class="card shadow-sm border-0"><div class="card-header bg-white"><h3 class="card-title font-weight-bold"><i class="fas fa-layer-group text-primary mr-1"></i>Campaign Sections</h3></div><div class="card-body p-0" id="content-wrapper">@include('backoffice.admin.campaign_sections.partials.table',['sections'=>$sections,'isTrash'=>false])</div></div>
</div>
<div class="modal fade" id="ajaxModal" data-backdrop="static" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header border-0"><h5 id="modal-title" class="modal-title font-weight-bold text-primary">Campaign Section</h5><button class="close" data-dismiss="modal">&times;</button></div><div class="modal-body" id="modal-body"></div></div></div></div>
@endsection
@section('plugins.Select2', true)
@section('plugins.Sweetalert2', true)
@section('js') @include('backoffice.admin.campaign_sections.partials.script') @endsection
