@extends('backoffice.admin.layouts.app')
@section('title',$title)
@section('content')
<div id="campaign-section-manager" class="container-fluid py-3" data-index-url="{{ route('admin.campaign_sections.trashed') }}" data-bulk-url="{{ route('admin.campaign_sections.multiple_action') }}">
<div class="d-flex align-items-center flex-wrap mb-3" style="gap:6px;"><a href="{{ route('admin.campaign_sections.index') }}" class="btn btn-secondary btn-sm font-weight-bold"><i class="fas fa-arrow-left mr-1"></i>Back</a><select id="bulk_action" class="form-control form-control-sm" style="width:210px;"><option value="">-- Bulk Actions --</option>@can('campaign_section_restore')<option value="restore">Restore Selected</option>@endcan @can('campaign_section_force_delete')<option value="force_delete">Permanently Delete</option>@endcan</select><button class="btn btn-secondary btn-sm font-weight-bold px-3" id="btnApplyBulk">APPLY</button></div>
<div class="card shadow-sm border-0 mb-3"><div class="card-body px-3 py-2"><form id="filterForm" action="{{ route('admin.campaign_sections.trashed') }}"><div class="row"><div class="col-md-4"><select name="campaign_id" id="filter_campaign" class="form-control form-control-sm"><option value="">All Campaigns</option>@foreach($campaigns as $c)<option value="{{ $c->id }}">{{ $c->title }}</option>@endforeach</select></div><div class="col-md-3"><select name="section_key" id="filter_type" class="form-control form-control-sm"><option value="">All Types</option>@foreach($types as $k=>$l)<option value="{{ $k }}">{{ $l }}</option>@endforeach</select></div><div class="col-md-4"><input name="search" id="table_search" class="form-control form-control-sm" placeholder="Search..."></div><div class="col-md-1"><button type="button" id="btnResetFilter" class="btn btn-outline-danger btn-sm btn-block"><i class="fas fa-sync-alt"></i></button></div></div></form></div></div>
<div class="card shadow-sm border-0"><div class="card-header bg-white text-danger"><h3 class="card-title font-weight-bold">Campaign Section Trash</h3></div><div class="card-body p-0" id="content-wrapper">@include('backoffice.admin.campaign_sections.partials.table',['sections'=>$sections,'isTrash'=>true])</div></div></div>
<div class="modal fade" id="ajaxModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header border-0"><h5 id="modal-title" class="modal-title font-weight-bold text-primary">Campaign Section</h5><button class="close" data-dismiss="modal">&times;</button></div><div class="modal-body" id="modal-body"></div></div></div></div>
@endsection
@section('plugins.Sweetalert2', true)
@section('js') @include('backoffice.admin.campaign_sections.partials.script') @endsection
